#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/TranscriberVCA.Generated/ && \
    dotnet build src/TranscriberVCA.Generated/ && \
    echo "Now, run the following to start the project: dotnet run -p src/TranscriberVCA.Generated/TranscriberVCA.Generated.csproj --launch-profile web"
