/*
 * TranscriberVCA
 *
 * Сервис транскрипции YouTube видео с помощью ИИ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using TranscriberVCA.Generated.Converters;

namespace TranscriberVCA.Generated.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TranscriptionResult : IEquatable<TranscriptionResult>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>228322a</example> */
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets YoutubeUrl
        /// </summary>
        /* <example>https://www.youtube.com/watch?v&#x3D;dQw4w9WgXcQ</example> */
        [DataMember(Name="youtube_url", EmitDefaultValue=false)]
        public string YoutubeUrl { get; set; }


        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ModelEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ModelEnum
        {
            
            /// <summary>
            /// Enum MiniEnum for mini
            /// </summary>
            [EnumMember(Value = "mini")]
            MiniEnum = 1,
            
            /// <summary>
            /// Enum BaseEnum for base
            /// </summary>
            [EnumMember(Value = "base")]
            BaseEnum = 2,
            
            /// <summary>
            /// Enum SmallEnum for small
            /// </summary>
            [EnumMember(Value = "small")]
            SmallEnum = 3,
            
            /// <summary>
            /// Enum MediumEnum for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            MediumEnum = 4,
            
            /// <summary>
            /// Enum LargeEnum for large
            /// </summary>
            [EnumMember(Value = "large")]
            LargeEnum = 5
        }

        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        /* <example>base</example> */
        [DataMember(Name="model", EmitDefaultValue=true)]
        public ModelEnum Model { get; set; }


        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<FormatEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum FormatEnum
        {
            
            /// <summary>
            /// Enum TxtEnum for txt
            /// </summary>
            [EnumMember(Value = "txt")]
            TxtEnum = 1,
            
            /// <summary>
            /// Enum JsonEnum for json
            /// </summary>
            [EnumMember(Value = "json")]
            JsonEnum = 2
        }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        /* <example>txt</example> */
        [DataMember(Name="format", EmitDefaultValue=true)]
        public FormatEnum Format { get; set; }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<StatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum ExtractingEnum for extracting
            /// </summary>
            [EnumMember(Value = "extracting")]
            ExtractingEnum = 1,
            
            /// <summary>
            /// Enum TranscribingEnum for transcribing
            /// </summary>
            [EnumMember(Value = "transcribing")]
            TranscribingEnum = 2,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 3,
            
            /// <summary>
            /// Enum ErrorEnum for error
            /// </summary>
            [EnumMember(Value = "error")]
            ErrorEnum = 4
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>completed</example> */
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public TranscriptionResultResult Result { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranscriptionResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  YoutubeUrl: ").Append(YoutubeUrl).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TranscriptionResult)obj);
        }

        /// <summary>
        /// Returns true if TranscriptionResult instances are equal
        /// </summary>
        /// <param name="other">Instance of TranscriptionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranscriptionResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    YoutubeUrl == other.YoutubeUrl ||
                    YoutubeUrl != null &&
                    YoutubeUrl.Equals(other.YoutubeUrl)
                ) && 
                (
                    Model == other.Model ||
                    
                    Model.Equals(other.Model)
                ) && 
                (
                    Format == other.Format ||
                    
                    Format.Equals(other.Format)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                ) && 
                (
                    CreatedAt == other.CreatedAt ||
                    
                    CreatedAt.Equals(other.CreatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (YoutubeUrl != null)
                    hashCode = hashCode * 59 + YoutubeUrl.GetHashCode();
                    
                    hashCode = hashCode * 59 + Model.GetHashCode();
                    
                    hashCode = hashCode * 59 + Format.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                    
                    hashCode = hashCode * 59 + CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TranscriptionResult left, TranscriptionResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TranscriptionResult left, TranscriptionResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
