/*
 * TranscriberVCA
 *
 * Сервис транскрипции YouTube видео с помощью ИИ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using TranscriberVCA.Generated.Converters;

namespace TranscriberVCA.Generated.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TranscribeRequest : IEquatable<TranscribeRequest>
    {
        /// <summary>
        /// Ссылка навидео
        /// </summary>
        /// <value>Ссылка навидео</value>
        /* <example>https://www.youtube.com/watch?v&#x3D;aArtkKEDaps</example> */
        [Required]
        [DataMember(Name="youtube_url", EmitDefaultValue=false)]
        public string YoutubeUrl { get; set; }


        /// <summary>
        /// Сложность модели транскрипции. Чем она сложнее, тем выше качество, но и дольше ожидание.
        /// </summary>
        /// <value>Сложность модели транскрипции. Чем она сложнее, тем выше качество, но и дольше ожидание.</value>
        [TypeConverter(typeof(CustomEnumConverter<ModelEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ModelEnum
        {
            
            /// <summary>
            /// Enum MiniEnum for mini
            /// </summary>
            [EnumMember(Value = "mini")]
            MiniEnum = 1,
            
            /// <summary>
            /// Enum BaseEnum for base
            /// </summary>
            [EnumMember(Value = "base")]
            BaseEnum = 2,
            
            /// <summary>
            /// Enum SmallEnum for small
            /// </summary>
            [EnumMember(Value = "small")]
            SmallEnum = 3,
            
            /// <summary>
            /// Enum MediumEnum for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            MediumEnum = 4,
            
            /// <summary>
            /// Enum LargeEnum for large
            /// </summary>
            [EnumMember(Value = "large")]
            LargeEnum = 5
        }

        /// <summary>
        /// Сложность модели транскрипции. Чем она сложнее, тем выше качество, но и дольше ожидание.
        /// </summary>
        /// <value>Сложность модели транскрипции. Чем она сложнее, тем выше качество, но и дольше ожидание.</value>
        [DataMember(Name="model", EmitDefaultValue=true)]
        public ModelEnum Model { get; set; } = ModelEnum.BaseEnum;


        /// <summary>
        /// Формат результата
        /// </summary>
        /// <value>Формат результата</value>
        [TypeConverter(typeof(CustomEnumConverter<FormatEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum FormatEnum
        {
            
            /// <summary>
            /// Enum TxtEnum for txt
            /// </summary>
            [EnumMember(Value = "txt")]
            TxtEnum = 1,
            
            /// <summary>
            /// Enum JsonEnum for json
            /// </summary>
            [EnumMember(Value = "json")]
            JsonEnum = 2
        }

        /// <summary>
        /// Формат результата
        /// </summary>
        /// <value>Формат результата</value>
        [DataMember(Name="format", EmitDefaultValue=true)]
        public FormatEnum Format { get; set; } = FormatEnum.TxtEnum;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranscribeRequest {\n");
            sb.Append("  YoutubeUrl: ").Append(YoutubeUrl).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TranscribeRequest)obj);
        }

        /// <summary>
        /// Returns true if TranscribeRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TranscribeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranscribeRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    YoutubeUrl == other.YoutubeUrl ||
                    YoutubeUrl != null &&
                    YoutubeUrl.Equals(other.YoutubeUrl)
                ) && 
                (
                    Model == other.Model ||
                    
                    Model.Equals(other.Model)
                ) && 
                (
                    Format == other.Format ||
                    
                    Format.Equals(other.Format)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (YoutubeUrl != null)
                    hashCode = hashCode * 59 + YoutubeUrl.GetHashCode();
                    
                    hashCode = hashCode * 59 + Model.GetHashCode();
                    
                    hashCode = hashCode * 59 + Format.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TranscribeRequest left, TranscribeRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TranscribeRequest left, TranscribeRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
